name: Test
on: [push, pull_request]
jobs:
  test:
    name: Test
    strategy:
      matrix:
        go: [1.12.x, 1.13.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}

      - name: Checkout code
        uses: actions/checkout@v1

      - name: Get dependencies
        run: go mod tidy

      - name: Test
        run: go test -v .
